json.id coupon.to_param
json.title coupon.title
json.category coupon.category
json.enabled coupon.enabled
json.start_time coupon.start_time
json.end_time coupon.end_time
json.money coupon.money.to_f
json.condition coupon.condition
json.additional_condition coupon.additional_condition
