json.id member.to_param
json.nickname member.nickname
json.gender member.gender
json.avatar member.avatar
json.level member.level
json.coin_total member.coin_total
json.verified member.verified
json.receive_message_notification member.receive_message_notification
json.receive_reply_notification member.receive_reply_notification
