class Article < ActiveRecord::Base
  # extends ...................................................................
  acts_as_paranoid
  encrypted_id key: 'AJ03lQmVmtomCfug'
  # includes ..................................................................
  include CarrierWave
  include ArticleFormatter
  # relationships .............................................................
  has_many :resources, :as => :resable
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order("position DESC") }
  scope :banner, -> { where(:banner => true) }
  scope :available, -> {
    where(
      "activate_at IS NULL OR (activate_at <= ? AND expire_at >= ?)",
      Date.today,
      Date.today
    )
  }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
