class Device < ActiveRecord::Base
  # extends ...................................................................
  encrypted_id key: 'zhKJmvPjguc33pvQ'
  # includes ..................................................................
  # relationships .............................................................
  has_one :device_info, :primary_key => "device_id"
  # validations ...............................................................
  validates :device_id, presence: true, uniqueness: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
