class Notification < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :application
  # validations ...............................................................
  validates :application_id, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # 刚注册的用户，发送第一条0元购的通知
  def self.send_sales_promotion_msg(device_id)
    device_info = DeviceInfo.where(device_id: device_id).first
    article_id = Article.where(title: "0元任你购 你想要我就敢送！").pluck(:id).first
    notification_info = {
      notice_type: "Article",
      notice_id: article_id,
      application_id: device_info.application_id,
      user_id: device_info.baidu_user_id,
      channel_id: device_info.baidu_channel_id,
      push_type: 1,
      message_type: 1,
      title: "0元购三天，您还等神马？！",
      description: "0元带性福回家，只对新用户只限3天！再不抢就没啦！！！"
    }
    self.create!(notification_info)
  end
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
