class Payment < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :order, touch: true
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  delegate :number, to: :order, prefix: true
  # class methods .............................................................
  # public instance methods ...................................................
  def process(amount)
    update_attribute(:amount, amount)
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
