class ProductProp < ActiveRecord::Base
  # extends ...................................................................
  encrypted_id key: 'F8qK9WWnWRtszMJP'
  # includes ..................................................................
  include EncryptedIdFinder
  # relationships .............................................................
  belongs_to :product
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  def out_of_stock
    # 自发货当做库存足够，醉清风库存量小于2天认为脱销
    rzx_validity.blank? ? false : rzx_validity < 2
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
