class Tactic < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  has_and_belongs_to_many :settings,
    class_name: "AdvertisementSetting",
    join_table: 'adv_settings_adv_tactics',
    foreign_key: 'adv_tactic_id'
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  self.table_name = "adv_tactics"
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
