class AdvStatistic < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  scope :by_app, ->(app_id) { where(application_id: app_id) }
  scope :by_advertisement, ->(advertisement_id) {
    where(adv_content_id: advertisement_id)
  }
  scope :today, -> {
    where(created_at: Date.today.midnight..Date.today.end_of_day)
  }
  scope :by_day, ->(day){ where(created_at: day.to_date.midnight..day.to_date.end_of_day) }
  scope :by_days, ->(n) {
    where(created_at: n.days.ago(Date.today).midnight..Date.today.end_of_day)
  }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  def increase_count(action, count)
    update_attribute("#{action}_count", send("#{action}_count") + count)
  end
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
