class AdvertisementSetting < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  has_and_belongs_to_many :tactics,
    join_table: 'adv_settings_adv_tactics',
    foreign_key: 'adv_setting_id',
    association_foreign_key: 'adv_tactic_id'
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { where(activity: true) }
  scope :by_channel_and_app, ->(channel, app) {
    settings = where(product_name: app.name, channel: channel)
    where(product_name: app.name, channel: "全部渠道") if settings.size.zero?
  }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  self.table_name = "adv_settings"
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
