class Application < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include EncryptedId
  # relationships .............................................................
  has_many :coupons
  has_many :resources, class_name: 'Resource'
  has_many :articles, through: :resources, source: :resable, source_type: "Article"
  has_many :advertisement_settings
  has_and_belongs_to_many :advertisements,
    join_table: 'adv_contents_applications',
    foreign_key: 'application_id',
    association_foreign_key: 'adv_content_id'

  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'VUUZzOQXNwx8HuyD'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
