class Article < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order("position DESC") }
  # additional config .........................................................
  mount_uploader :image, ImageUploader
  mount_uploader :background, BackgroundUploader
  encrypted_id key: '5gA6lgr5g3GOg7EOQ1caYQ'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
