class Article < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order("position DESC") }
  scope :banner, -> { where(:banner => true) }
  scope :with_free, -> { where(:banner => true) }
  scope :without_free, -> { where(:banner => true) }
  # additional config .........................................................
  mount_uploader :image, ImageUploader
  mount_uploader :background, BackgroundUploader
  encrypted_id key: 'AJ03lQmVmtomCfug'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
