class Blacklist < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  validates_uniqueness_of :device_id, :scope => :node_id
  # callbacks .................................................................
  # scopes ....................................................................
  scope :available, -> { where("free_at IS NULL OR free_at > ?", Date.today) }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  self.table_name = "block_lists"
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
