class Cart < ActiveRecord::Base
  # extends ...................................................................
  acts_as_paranoid
  encrypted_id key: 'XrFP2VnzrWvobm9F'
  # includes ..................................................................
  # relationships .............................................................
  has_many :line_items
  # validations ...............................................................
  validates :device_id, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  accepts_nested_attributes_for :line_items
  # class methods .............................................................
  def clear_items!
    line_items.destroy_all
  end
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
