class Comment < ActiveRecord::Base
  # extends ...................................................................
  acts_as_paranoid
  # includes ..................................................................
  include EncryptedId
  # relationships .............................................................
  belongs_to :order
  belongs_to :commable, polymorphic: true
  # validations ...............................................................
  # callbacks .................................................................
  after_initialize :set_comment_time
  # scopes ....................................................................
  default_scope { where(:enabled => true).order("id DESC") }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'vL6dUuuJn0yLMdYd'
  DEFAULT_SCORE = 5

  alias_attribute :product_quality_score, :score
  # class methods .............................................................
  # public instance methods ...................................................
  def express_score
    order.comment.score || DEFAULT_SCORE
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

  def set_comment_time
    self.comment_at = Time.now
  end
end
