class Content < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include EncryptedId
  include Voting
  # relationships .............................................................
  has_many :replies, -> { order "created_at DESC" }, as: :replyable, :dependent => :destroy
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { where(approved: true).order("top DESC, id DESC") }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'N2kTa8dyAyRtkdTz'
  alias_attribute :body, :text
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
