class Coupon < ActiveRecord::Base
  # extends ...................................................................
  encrypted_id key: 'pVXy9ChXEe2Fmmfa'
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_and_belongs_to_many :orders
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  scope :by_device, ->(device_id) { where(:to => [device_id, 'ALL']) }
  scope :enabled, -> { where(enabled: true) }
  scope :separate, -> { where(separate: true) }
  scope :available_for, ->(t) {
    enabled.where("start_time <= ? AND end_time >= ?", t, t)
  }


  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def used!
    new_number = number - 1
    new_number = new_number < 0 ? 0 : new_number
    update_attribute(:number, new_number)
    update_attribute(:enabled, false) if new_number == 0
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
