class Favorite < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include EncryptedId
  # relationships .............................................................
  belongs_to :favable, :polymorphic => true
  # validations ...............................................................
  validates_uniqueness_of :device_id, :scope => [:favable_id, :favable_type]
  # callbacks .................................................................
  # scopes ....................................................................
  scope :by_device_id, ->(device_id) { where(device_id: device_id) }
  scope :by_favable, ->(favable) {
    where(favable_type: favable.class.name, favable_id: favable.id)
  }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'fv8gz8VZiDPMqXMJ'
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
