class Homepage < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  has_many :contents, class_name: "HomeContent", foreign_key: :page_id
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { where(activity: true) }
  scope :by_hour, ->(t) { where(hour: [0, t]).order("hour DESC") }
  scope :for_app, ->(app) { where(application_id: [app.id, 0]) }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
