class OperatingAgent
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  def self.wechat_activitie(member_id, device_id)
    agent = self.new
    agent.wechat_activitie(member_id, device_id)
  end
  # public instance methods ...................................................
  def wechat_activitie(member_id, device_id)
    message = send_an_invitation_private_mesage_to_member(member_id)
    push_an_invitation_notification_to_member(device_id) if message
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

  def send_an_invitation_private_mesage_to_member(member_id)
    PrivateMessage.send_an_invitation_to_member(member_id)
  end

  def push_an_invitation_notification_to_member(device_id)
    Notification.send_private_message_msg(device_id) if device_id
  end

end
