class Order < ActiveRecord::Base
  # extends ...................................................................
  acts_as_paranoid
  encrypted_id key: 'bYqILlFMZn3xd8Cy'
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :comments
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  scope :by_filter, ->(filter) { filter == :rated ? with_comments : self }
  scope :with_comments, -> { joins(:comments) }
  # additional config .........................................................
  # class methods .............................................................
  # def self.by_filter(filter)
  #   filter == :rated ? self.with_comments : self
  # end
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
