class ProductProp < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include EncryptedId
  # relationships .............................................................
  belongs_to :product
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order("rzx_stock DESC") }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'F8qK9WWnWRtszMJP'
  # class methods .............................................................
  # public instance methods ...................................................
  def out_of_stock
    quantity == 0
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
