class ProductProp < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  include EncryptedId
  # relationships .............................................................
  belongs_to :product
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order("rzx_stock DESC") }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'F8qK9WWnWRtszMJP'
  # class methods .............................................................
  # public instance methods ...................................................
  def out_of_stock
    quantity == 0
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
  #市场价格
  scope :retail_price, -> {
    #如果库存相同优先展示价格低的
    reorder("rzx_stock DESC, sale_price ASC").first.sale_price
  }
end
