class Product < ActiveRecord::Base
  # extends ...................................................................
  acts_as_taggable_on :tags
  mount_uploader :image, ImageUploader
  encrypted_id key: 'XRbLEgrUCLHh94qG'
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :product_props
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order("rank DESC") }
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def market_price
    # 顯示最高的原價
    product_props.order("original_price DESC").first.original_price
  end

  def retail_price
    # 顯示最低的賣價
    product_props.order("sale_price").first.sale_price
  end

  def labels
    Tag.for_popularize.collect(&:name) & tag_list
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
