class Setting < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  scope :transport_settings, -> { where(name: TRANSPORT_SETTING) }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  TRANSPORT_SETTING = [
    :online_shipping_fee, :online_free_shipping_conditione, :online_description,
    :cash_shipping_fee, :cash_free_shipping_conditione, :cash_description
  ]
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
