class Tactic < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  has_and_belongs_to_many :settings,
    class_name: "AdvertisementSetting",
    join_table: 'adv_settings_adv_tactics',
    foreign_key: 'adv_tactic_id'
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  self.table_name = "adv_tactics"
  serialize :adv_content_ids
  # class methods .............................................................
  # public instance methods ...................................................
  def adv_content_ids
    if self[:adv_content_ids]
      format_id = Proc.new { |id| id.to_i if id }
      self[:adv_content_ids].collect(&format_id).select { |id| id != 0 }
    end
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
