class Tag < ActiveRecord::Base
  # extends ...................................................................
  acts_as_nested_set
  # includes ..................................................................
  include CarrierWaveMini
  # relationships .............................................................
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  scope :for_home, lambda { where(id: Tag::CATEGORIES) }
  scope :for_popularize, lambda { where(category: "Popularize").order(:id) }
  scope :banner, -> { where(:banner => true) }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  CATEGORIES = [1, 8, 3, 5, 6, 7, 4, 114]
  alias_attribute :title, :name
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
